export const TAGS = {
  workorders: 'Work Orders',
  tasks: 'Tasks',
  expenses: 'Expenses',
  priceList: 'Price List',
  invoices: 'Invoices',
  quotes: 'Quotes',
  clients: 'Clients',
  users: 'Users',
  roles: 'Roles',
  settings: 'Settings',
  reminders: 'Reminders',
  auditLogs: 'Audit Logs',
  business: 'Business',
  insights: 'Insights',
}
